version: '3.9'
services:
  avito-parser:
    build: .
    container_name: avito-parser-d
    volumes:
      - ./result:/app/result
      - ./settings.ini:/app/settings.ini
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
